# MongoDB
spring:
  data:
    mongodb:
#      host: 192.16.8.133
#      port: 27017
#      username: coracle
#      password: Cor2018
#      authentication-database: admin
      database: test
      uri: mongodb://coracle:Cor2018@192.16.8.133:27017/admin

### 连接池设置为300个连接,默认为100
#mongodb.pool.connectionsPerHost=100
### 连接超时，推荐>3000毫秒
#mongodb.pool.connectTimeout=30000
### 最大等待可用连接的时间
#mongodb.pool.maxWaitTime=60000
### 套接字超时时间，0无限制
#mongodb.pool.socketTimeout=0
### 连接的最大闲置时间，0：表示无限制。
#mongodb.pool.maxConnectionIdleTime=0
### 连接的最大生存时间，0：表示无限制。
#mongodb.pool.maxConnectionLifeTime=0
### 线程队列数，如果连接线程排满了队列就会抛出“Out of semaphores to get db”错误。
#mongodb.pool.threadsAllowedToBlockForConnectionMultiplier=10
