# Redis
spring:
  redis:
    # Redis单节点模式
    host: 192.16.8.133
    port: 6379
    password: Cor@2018
    # 连接超时时间（毫秒）
    timeout: 5000
    pool:
      # 连接池中的最大空闲连接
      max-idle: 100
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 1024
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最小空闲连接
      min-idle: 0
