# 服务端口
server:
  port: 8760

# 服务名
spring:
  application:
    name: zuul

# Eureka
eureka:
  client:
    # 刷新本地缓存时间，默认30s
    registry-fetch-interval-seconds: 1

# Ribbon
ribbon:
  # Ribbon缓存刷新时间，默认为30秒
  ServerListRefreshInterval: 1000
  # 需考虑降低Ribbon的读取与连接超时上限
  read-timeout: 60000
  connect-timeout: 20000

# Spring Security配置
security:
  basic:
    # 是否开启基本的认证，默认为true
    enabled: false
  oauth2:
    client:
      # 指定获取access token的url
      access-token-uri: http://localhost:8760/uaa/oauth/token
      # 用户跳转去获取access token的url
      user-authorization-uri: http://localhost:8760/uaa/oauth/authorize
    resource:
      # 指定user info的url
      user-info-uri: http://localhost:8760/uaa/user
      # 是否使用token info，默认为true
      prefer-token-info: false

# Zuul
zuul:
  routes:
    order:
      path: /order/**
      serviceId: dms-order
    order-zzy:
      path: /order-zzy/**
      serviceId: dms-order-zzy
    order-hxj:
      path: /order-hxj/**
      serviceId: dms-order-hxj
    dictionary:
      path: /dictionary/**
      serviceId: dictionary
    info:
      path: /info/**
      serviceId: info
    schedule:
      path: /schedule/**
      serviceId: schedule
    uaa:
      path: /uaa/**
      serviceId: uaa
    uaa-ldz:
      path: /uaa-ldz/**
      serviceId: uaa-ldz
    message:
      path: /message/**
      serviceId: message
  add-host-header: true
  sensitive-headers: 
#  host:
#    connect-timeout-millis: 10000
#    socket-timeout-millis: 60000
    
##熔断超时配置 未测试
#hystrix:  
#  command:  
#    default:  
#      execution:  
#        isolation:  
#          thread:  
#            timeoutInMilliseconds: 60000
